"""empty message

Revision ID: 4933147d81b9
Revises: 
Create Date: 2021-12-05 16:58:25.061478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4933147d81b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('creation_date', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_title'), 'ad', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_title'), table_name='ad')
    op.drop_table('ad')
    # ### end Alembic commands ###
